apiVersion: v1
kind: Service
metadata:
  name: {{.Values.deployment.app_name}}
  namespace: {{.Values.namespace}}  
spec:
  selector:
    app: {{.Values.deployment.app_name}}
  ports:
  - protocol: TCP
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
  type: {{.Values.service.type}}
